### ISSUE TITLE
Add non-copying methods.

### ISSUE THREAD

**Issue by TyOverby** [PistonDevelopers/vecmath#202]
I'd like to have functions like this:

```rust
fn col_mat4_mul_ref<A>(left: &mut [[A,..4], ..4], right: &[[A, ..4], ..4]) {
    ...
}
```

I think that if you implemented these functions, you could implement your existing functions based on these new ref-taking functions.

**Comment by bvssvni** [comment]
Closing this because I think compiler optimization should take care of this.
