### ISSUE TITLE
Add conversion between radians and degrees

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/vecmath#208]
By making `Radians` inherit `FromPrimitive`, it can convert between radians and degrees.

```Rust
let x: f64 = 90.0;
x.deg_to_rad()
x.rad_to_deg()
```

**Comment by burtonageo** [comment]
I have created an initial implementation of this in #214. Comments and criticisms welcome

**Comment by ruud-v-a** [comment]
A note on the types (though they were there before this issue), having a `Radians` trait but not `Degrees` creates an asymmetry, although there is (and should be) no clear default unit. We could be more explicit with newtypes. E.g. now you can do `60f32.to_rad().to_rad()` which makes no sense. Type-safe units can be achieved with newtypes, i.e.

```rust
struct Radians<T: Float>(T);
struct Degrees<T: Float>(T);
```

with conversion functions `fn to_rad(self) -> Radians<T>` on `Degrees` and `to_deg` on `Radians`, however, such wrappers are more cumbersome to work with (with might be an advantage in some situations as well, you can’t accidentally add degrees and radians, for example).

**Comment by bvssvni** [comment]
Perhaps rename to `deg_to_rad`?

**Comment by ruud-v-a** [comment]
> Perhaps rename to `deg_to_rad`?

That would be a good compromise between clarity and type safety, I think.

**Comment by bvssvni** [comment]
Opened https://github.com/PistonDevelopers/vecmath/issues/215
