### ISSUE TITLE
Add Operators

### ISSUE THREAD

**Issue by burtonageo** [PistonDevelopers/vecmath#213]
It's natural to express vector/matrix maths using standard mathematical symbols. Perhaps we could add a ```vecmath::ops``` module, with ```vecmath::ops::row_major``` and ```vecmath::ops::col_major``` submodules for row/column major operations.

**Comment by burtonageo** [comment]
This is impossible as it would require #![feature(old_orphan_check)] due to the fact that vectors/matrices are type aliases and not newtypes/structs

**Comment by bvssvni** [comment]
This library is type agnostic by naming the operations, to be as easy as possible to reason about. There is no difference between row vs column major except how the operations are performed.
