### ISSUE TITLE
Incorrect naming

### ISSUE THREAD

**Issue by dhardy** [PistonDevelopers/vecmath#218]
From lib.rs:

    /// A 3D vector.
    pub type Vector3<T> = [T; 3];

It's not three-dimensional; it just has three elements.

Sorry for the stupid report; it just mis-lead me briefly..

**Comment by bvssvni** [comment]
Naming usually goes by usage and not structural definition, unless the structure has a background in common or academic knowledge. A type like `[T; 3]` is too simple to be interpreted on its own.

**Comment by dhardy** [comment]
It looks like a 1D array, but as you say it is possible to build other things with it. The comment "2D vector" is either way incorrect. 

On Mon Jan 26 19:00:46 2015 GMT+0100, Sven Nilsen wrote:
> Naming usually goes by usage and not structural definition, unless the structure has a background in common or academic knowledge. A type like `[T; 3]` is too simple to be interpreted on its own.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/PistonDevelopers/vecmath/issues/218#issuecomment-7150599

-- 
Sent from my Jolla

**Comment by bvssvni** [comment]
For a moment I thought the comment said `2D` on `Vector3`, but the source seems to be correct.

**Comment by bvssvni** [comment]
Closing?

**Comment by dhardy** [comment]
Nah, it was just the comment "A 3D vector". Sorry for the confusion.
