### ISSUE TITLE
Add a similarity function between vectors

### ISSUE THREAD

**Issue by boghison** [PistonDevelopers/vecmath#267]
It is possible to compute the similarity between vectors by using cosine similarity.

**Comment by bvssvni** [comment]
The vecmath library is for the most basic vector operations. It is designed for reexport in other libraries, for example https://github.com/PistonDevelopers/graphics/blob/master/src/math.rs. Different libraries have different needs for mathematical functions.

**Comment by boghison** [comment]
@bvssvni Is this issue invalid?

**Comment by bvssvni** [comment]
It is possible to compute the value by taking the dot product of two vectors and dividing by their lengths. The dot product of two normalized vectors is equal to the cosine similarity. I haven't used it much before as a single function. The usual way I do it is using normalized vectors.

**Comment by boghison** [comment]
@bvssvni Yes, I am aware of how one computes the cosine similarity of two vectors. Should this be implemented or not?

**Comment by bvssvni** [comment]
@boghison Do you need it for a project?

**Comment by boghison** [comment]
@bvssvni I don't, but I think this would be a fitting addition.

**Comment by bvssvni** [comment]
Do you have a suggestion for name? `vecX_cos_similarity` perhaps?

Alternative is to wait until somebody needs it.

**Comment by boghison** [comment]
@bvssvni Yes, that name sounds fine to me.

**Comment by bvssvni** [comment]
An optimization can be done by multiplying the dot product with itself and divide by the square lengths of the vectors. Then a square root can be used once at the end.

**Comment by bvssvni** [comment]
I don't think we should implement this now since nobody needs it.

Closing.
