### ISSUE TITLE
Consider using `mint` types

### ISSUE THREAD

**Issue by kvark** [PistonDevelopers/vecmath#271]
Follow-up to #270

I followed `vecmath`/`quaternion` types because I think they are reasonable, and it's great to be consistent with existing solutions. I want `mint` to become a standard of math interop, and I see a special place of `vecmath` in the future ecosystem: a math library (or, libraries, considering quaternion stuff) that simply work with standard types directly by defining traits and functions on them, contrary to other libraries that will have `From`/`Into` conversions.

Strictly speaking, you don't need to depend on `mint`, and then the agreement to use the same types will just be informal.

https://github.com/kvark/mint

**Comment by bvssvni** [comment]
Great idea!

**Comment by kvark** [comment]
@bvssvni it happened, strangely, that `mint` is getting strong types. The philosophy now is to have only the types and conversions, with no actual math/computations/traits.
That also means that `vecmath` is not compatible with `mint` any more :(
